export const russianLanguage = {
  mainPage: 'Главная страница',
  payments: 'Платежи',
  transfers: 'Трансферы',
  cards: 'Карты',
  myCards: 'Мои карты',
  cardProducts: 'Карточные продукты',
  loans: 'Кредиты',
  myLoans: 'Мои кредиты',
  loanProducts: 'Кредитные продукты',
  applyForALoan: 'Подать заявку на кредит',
  deposits: 'Депозиты',
  investing: 'Инвестирование',
  insurance: 'Страхование',
  dealsAndOffers: 'Сделки и предложения',
} as const;

export const englishLanguage = {
  mainPage: 'Main page',
  payments: 'Payments',
  transfers: 'Transfers',
  cards: 'Cards',
  myCards: 'My cards',
  cardProducts: 'Card products',
  loans: 'Loans',
  myLoans: 'My loans',
  loanProducts: 'Loan products',
  applyForALoan: 'Apply for a loan',
  deposits: 'Deposits',
  investing: 'Investing',
  insurance: 'Insurance',
  dealsAndOffers: 'Deals & offers',
} as const;

export const PATH = {
  mainPage: '/',
  payments: '/payments',
  transfers: '/transfers',
  cards: '/my_cards',
  myCards: '/my_cards',
  cardProducts: '/card_products',
  loans: '/my_loans',
  myLoans: '/my_loans',
  loanProducts: '/loan_products',
  applyForALoan: '/apply_for_a_loan',
  deposits: '/deposits',
  investing: '/investing',
  insurance: '/insurance',
  dealsAndOffers: '/deals&Offers',
}
