export const defaultFormData = {
  answer: '',
  confirmPassword: '',
  password: '',
  question: '',
  questions: '',
  smsCode: '',
  telephone: '',
  passport: '',
  name: '',
  surname: '',
  patronymic: '',
  income: '',
  month: '',
  salary: '',
  expense: '',
  ein: '',
};

export const defaultFormValid = {
  answer: false,
  confirmPassword: false,
  password: false,
  question: false,
  questions: false,
  smsCode: false,
  telephone: false,
  passport: false,
  name: false,
  surname: false,
  patronymic: true,
  income: false,
  ein: false,
};
