export const russianLanguage = {
  mainPage: 'Главная страница',
  payments: 'Платежи',
  transfers: 'Трансферы',
  cards: 'Карты',
  myCards: 'Мои карты',
  cardProducts: 'Карточные продукты',
  loans: 'Кредиты',
  myLoans: 'Мои кредиты',
  loanProducts: 'Кредитные продукты',
  applyForALoan: 'Подать заявку на кредит',
  deposits: 'Депозиты',
  investing: 'Инвестирование',
  insurance: 'Страхование',
  dealsAndOffers: 'Сделки и предложения',
} as const;

export const englishLanguage = {
  mainPage: 'Main page',
  payments: 'Payments',
  transfers: 'Transfers',
  cards: 'Cards',
  myCards: 'My cards',
  cardProducts: 'Card products',
  loans: 'Loans',
  myLoans: 'My loans',
  loanProducts: 'Loan products',
  applyForALoan: 'Apply for a loan',
  deposits: 'Deposits',
  investing: 'Investing',
  insurance: 'Insurance',
  dealsAndOffers: 'Deals & offers',
} as const;

export const PATH = {
  mainPage: '/main',
  payments: '/main/payments',
  transfers: '/main/transfers',
  cards: '/main/my_cards',
  myCards: '/main/my_cards',
  cardProducts: '/main/card_products',
  loans: '/main/my_loans',
  myLoans: '/main/my_loans',
  loanProducts: '/main/loan_products',
  applyForALoan: '/main/apply_for_a_loan',
  deposits: '/main/deposits',
  investing: '/main/investing',
  insurance: '/main/insurance',
  dealsAndOffers: '/main/deals&Offers',
}
